package components

var catalogDatabases = Section{
	Name: "Databases",
	Items: []InstallItem{
		{
			Name:    "MySQL",
			Desc:    "Relational database using SQL for structured data storage",
			Formula: "mysql",
			Color:   rgb(50, 190, 230),
			Binary:  "mysql",
		},
		{
			Name:    "PostgreSQL",
			Desc:    "Object-relational database for complex workloads and data integrity",
			Formula: "postgresql",
			Color:   rgb(100, 160, 220),
			Binary:  "psql",
		},
		{
			Name:    "MariaDB",
			Desc:    "Relational database based on the original MySQL engine",
			Formula: "mariadb",
			Color:   rgb(230, 150, 120),
			Binary:  "mariadb",
		},
		{
			Name:    "CockroachDB",
			Desc:    "Distributed SQL database for resilient cloud-native applications",
			Formula: "cockroachdb/tap/cockroach",
			Color:   rgb(105, 190, 150),
			Binary:  "cockroach",
		},
		{
			Name:    "TimescaleDB",
			Desc:    "Relational database optimized for time-series and analytical use",
			Formula: "timescale/tap/timescaledb",
			Color:   rgb(120, 180, 240),
		},
		{
			Name:    "MongoDB",
			Desc:    "NoSQL document database using flexible JSON-like schemas",
			Formula: "mongodb/brew/mongodb-community",
			Color:   rgb(100, 220, 100),
			Binary:  "mongod",
		},
		{
			Name:    "SQLite",
			Desc:    "Serverless relational database engine for local storage",
			Formula: "sqlite",
			Color:   rgb(140, 230, 255),
			Binary:  "sqlite3",
		},
		{
			Name:    "ClickHouse",
			Desc:    "Columnar database for high-performance analytical queries",
			Formula: "clickhouse",
			Color:   rgb(255, 210, 50),
			Binary:  "clickhouse",
		},
		{
			Name:    "ElasticSearch",
			Desc:    "Distributed search and analytics engine for large-scale text",
			Formula: "elasticsearch",
			Color:   rgb(20, 190, 180),
			Binary:  "elasticsearch",
		},
		{
			Name:    "Neo4j",
			Desc:    "Graph database system for connected data and relationships",
			Formula: "neo4j",
			Color:   rgb(0, 150, 230),
			Binary:  "neo4j",
		},
		{
			Name:    "Firebase CLI",
			Desc:    "Management tools for Firebase applications and deployments",
			Special: "npm-g",
			Formula: "firebase-tools",
			Color:   rgb(255, 200, 50),
			Binary:  "firebase",
		},
		{
			Name:    "Supabase CLI",
			Desc:    "Local development and management for the Supabase platform",
			Formula: "supabase/tap/supabase",
			Color:   rgb(60, 200, 130),
			Binary:  "supabase",
		},
	},
}
